### ISSUE TITLE
Add a original photos to readme and slider

### ISSUE THREAD

**Issue by JelteF** [alexjc/neural-enhance#29]
It would be nice to be able to see the original of the photo as well, instead of only the pixelated one and the enhanced one.
That way you can see how close the enhanced version is to reality.  For instance the chinese symbols enhancement really seems to improve legibility by an amazing amount, but maybe it's totally off and showing wrong symbols.

**Comment by alexjc** [comment]
The online demo with slider only uses/stores the low-resolution image and does not keep the original, so I can't add it there. You are free to download the SR version and compare it yourself; just click the download button or use Save As...

For the README, I added the link to the original image too. In the GIF, it didn't work to add the original image due to 8-bit quantization it didn't look very good.  People experienced with images can easily just download everything and compare offline.
