### ISSUE TITLE
2x‘s effect is not good

### ISSUE THREAD

**Issue by eeric** [alexjc/neural-enhance#62]
for ne2x-small-0.2.pkl.bz2 modle, but its effect isn't well as  2 times size of original image, why?

**Comment by nagadomi** [comment]
I tried to benchmark  `ne2x-small-0.2` on BSD100 dataset(testset of BSDS300), then the PSNR is lower than Bicubic.

|  | Bicubic | ne2x-small-0.2 **1*  | waifu2x/photo **2* |
| ---------------- | ---------- | --------------------- | -------------------- |
| BSD100 2x PSNR **3*    | 29.558  | 26.675               |              31.749 |

\*1: `python enhance.py --device=gpu0 --model=small --zoom 2 bsd100/*`
\*2: `find bsd100 -name "*.png" > list.txt; mkdir bsd100_waifu2x; th waifu2x.lua -model_dir models/upconv_7/photo -m scale -l list.txt -o bsd100_waifu2x/%s.png`
\*3: higher value is better

A while ago I tested 4x on `0.1`. The results seemed good. I think `0.2` pretrained models are specialized(or overfitting)  for the training settings.

**Comment by alexjc** [comment]
@eeric Try rolling back to `v0.1` branch and trying those models. Also, please include an example if this is a bug report.

@nagadomi The `v0.2` trained models are trained on 500k images with more blur and noise so they work more reliably on real images, rather than images that are downsampled for testing. Down-sampled images are easier to handle (as in `v0.1`), but as users reported here they were not representative of the cases people had with actual low quality images to enhance.

Looks like it's over-specializing on the blur scenario, these results are very good, the rest not:
![csi_56371107_facb6301d7_b](https://cloud.githubusercontent.com/assets/445208/20101871/1646c446-a5c4-11e6-89f7-673d0d538bc3.jpg)
![csi_56371107_facb6301d7_b_ne1x](https://cloud.githubusercontent.com/assets/445208/20101876/18d06cd0-a5c4-11e6-81ce-aefe8e8b5619.png)

**Comment by nagadomi** [comment]
I think that the deblur model only works for blurred images. When the input image is not blurred, the model will create lots of ringing artifacts like sharpen filter.
My suggestion is below:
1. separate the model by each domain. (ne1x-deblur, ne1x-jpeg, ...), Or
2. use combined dataset in training (blurred images + clear images + ...)

**Comment by alexjc** [comment]
@nagadomi Thanks for the suggestion. It's doing 2 already with various blur settings and without, but apparently there's not enough NN capacity to handle this. Likely will separate the models...

**Comment by eeric** [comment]
I used images that are downsampled for testing, so its effect is bad.
Ok, thanks for your advice.

**Comment by alexjc** [comment]
Try again on `v0.3` with `--type=photo --zoom=2`. If there are new issues feel free to report.
